version: '3'

services:
  app:
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}